version: '3.9'

services:
  azurite:
    container_name: azurite
    build:
      context: .
      dockerfile: infra/local/azurite/Dockerfile
    volumes:
      - azurite:/workspace
    ports:
      - 10000:10000

  dotnet:
    container_name: dotnet
    build:
      context: .
      dockerfile: infra/local/dotnet/Dockerfile
      args:
        ENVIRONMENT: $DOTNET_ENVIRONMENT
    volumes:
      - dotnet:/usr/share/nginx/html
    ports:
      - 8080:8080
    depends_on:
      - azurite

  # node:
  #   container_name: node
  #   build:
  #     context: .
  #     dockerfile: infra/local/node/Dockerfile
  #   volumes:
  #     - node:/app
  #   ports:
  #     - 3000:80
  #   depends_on:
  #     - dotnet

  # postgres:
  #   container_name: postgres
  #   build:
  #     context: .
  #     dockerfile: infra/local/postgres/Dockerfile
  #     args:
  #       USERNAME: $DB_USERNAME
  #       PASSWORD: $DB_PASSWORD
  #       DATABASE: $DB_DATABASE
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - postgres:/var/lib/postgresql/data

volumes:
  azurite:
  dotnet:
  # node:
  # postgres:
