name: Build

on:
  pull_request:
    branches:
      - main
  workflow_call:
    inputs:
      build-artifacts:
        type: boolean
        required: true
        default: false
  workflow_dispatch:

jobs:
  build-infra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      # TODO: validate bicep
      - name: Upload an ARM template artifact
        uses: actions/upload-artifact@v4
        with:
          name: infra
          path: infra/azure/**
          if-no-files-found: error

  build-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
      - name: Restore dependencies
        working-directory: server
        run: dotnet restore
      - name: Build
        working-directory: server
        run: dotnet build --no-restore --configuration Release
      - name: Test
        working-directory: server
        run: dotnet test --no-build --configuration Release --verbosity normal
      - name: Publish
        working-directory: server
        run: dotnet publish ${{ inputs.project-path }} --configuration Release --output output
      - name: Upload a build artifact
        if: ${{ inputs.build-artifacts == true }}
        uses: actions/upload-artifact@v4
        with:
          name: server
          path: server/output/**
          if-no-files-found: error

  build-web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
      - name: Upload a build artifact
        if: ${{ inputs.build-artifacts == true }}
        uses: actions/upload-artifact@v4
        with:
          name: web
          path: web/build/**
          if-no-files-found: error
