name: Deploy Static Web App

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Set server url base env
        run: echo "REACT_APP_SERVICE_URL=${{ secrets.SERVER_BASE_URL }}" >> $GITHUB_ENV

      - name: Set server url base env
        run: echo "REACT_APP_PUBLIC_URL=zpi-project" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: web/build

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
